spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/follow_sys?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jxd.follow_sys.model
