spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/follow_sys
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.jxd.follow_sys.model
